subjects = {
	"subjchoose":"Choose a subject...",
	"1st":"1st semester",
	"calc1":"Matematics I - Calculus I",
	"dimat1":"Discrete Mathematics and Linear Algebra I",
	"swddI":"Software Design and Development I",
	"electri":"Electricity / Electrical Engineering",
	"basinf":"Basics of Information Systems",
	"macro":"Macroeconomics",
	"2nd":"2nd semester",
	"calc2":"Calculus II",
	"dimat2":"Discrete Mathematics and Linear Algebra II",
	"physics":"Physics",
	"micro":"Microeconomics",
	"swdd2":"Software Design and Development II",
	"electro":"Electronics",
	"compnet":"Computer Networks",
	"3rd":"3rd semester",
	"enteco1":"Enterprise Economics I",
	"webadvprog":"Web Programming and Advanced Development Techniques",
	"webprog":"Web Programming in Java",
	"advdev":"Advanced development techinques",
	"datab":"Databases",
	"systheo":"System Theory",
	"digit":"Digital Systems",
	"opre":"Operating Systems",
	"4th":"4th semester",
	"probtheo":"Probability Theory and Mathematical Statistics",
	"enteco2":"Enterprise Economics II",
	"infocomm":"Infocommunication Techniques",
	"gui":"Software Technology and GUI Design",
	"intel":"Intelligent Systems",
	"itsec":"IT Security",
	"projwork4":"Project Work 4th semester",
	"5th":"5th semester",
	"management":"Basics of Management",
	"archi":"Introduction to Computer Architectures",
	"eis":"Enterprise Information Systems",
	"projwork5":"Project Work 5th semester",
	"6th":"6th semester",
	"law":"Public Administration and Law",
	"advarchi1":"Advanced Computer Architectures I",
	"projwork6":"Project Work 6th semester",
	"thesis1":"Thesis I",
	"7th":"7th semester",
	"advarchi2":"Advanced Computer Architectures II.",
	"projwork7":"Project Work 7th semester",
	"thesis2":"Thesis II",
	"IOT":"(J) IOT, Embedded Systems and Robotics Specialization",
	"contreng":"Control Engineering",
	"embedded":"Embedded and Sensor Based Systems",
	"robotics":"Introduction to Robotics",
	"embeddedprog1":"Embedded Programming I",
	"robotprog":"Introduction to Robot Programing",
	"embeddedprog2":"Embedded Programming II",
	"robot control":"Robot Control",
	"sensnet":"Sensor Networks, IoT Systems",
	"BigData":"(B) Big Data and Business Intelligence Specialization",
	"finance":"Introduction to Finance and Accounting of Enterprises",
	"advdb":"Advanced Databases",
	"warehousing":"Data Warehousing and Business Intelligence",
	"bigdataprog":"Big Data Algorithms and Programming",
	"erp1":"Enterprise Resource Planning I",
	"erp2":"Enterprise Resource Planning II",
	"Cloud":"(C) Cloud Service Technologies and IT Security Specialization",
	"nettech1":"Network Technologies I",
	"vis":"Virtualised Storage Systems",
	"ccs1":"Cloud Computing Services I",
	"ccs2":"Cloud Computing Services II",
	"secucomp":"Security of Computer Networks and Clouds",
	"secuinfosys":"Security of Information Systems and Services",
	"institutionsec":"Institution Information Security",
	"nettech2":"Network Technologies II",
	"virtual":"Technologies of Virtualised Networks and Data Centers",
	"Software":"(T) Software Design and Development Specialization",
	"parallel":"Parallel Programing",
	"largesw":"Developing Large Software Systems",
	"dataparallel":"Data-parallel Programming",
	"modernsw":"Modern Software Technology",
	"adval":"Advanced Algorithms",
	"testing":"Software Testing",
	"oop":"Advanced Object-Oriented Programming",
	"datastruct":"Advanced Data Structures",
	"script":"Interpreter and Script Languages",
	"deeplearn":"Deep Learning",
	"imagefund":"Fundamentals of Image Processing",
	"imageanalyses":"Image Analyses and Computer Vision",
	"android1":"Android Development I",
	"android2":"Android Development II",
	"iOS":"iOS-based Development",
	"JEE":"JEE Development",
	"WebDev":"Web Development",
	"AdvDataProc":"Advanced Data Processing"
}
credits = { // To understand: the first one is the index of the object in subjects, then the credit
	//1st semester
	"calc1":6,
	"dimat1":6,
	"swddI":6,
	"electri":5,
	"basinf":4,
	"macro":2,
	//2nd semester
	"calc2":6,
	"dimat2":5,
	"physics":5,
	"micro":2,
	"swdd2":6,
	"electro":4,
	"compnet":4,
	//3rd semester
	"enteco1":2,
	"webadvprog":5,
	"webprog":3,
	"advdev":4,
	"datab":5,
	"systheo":5,
	"digit":5,
	"opre":5,
	//4th semester
	"probtheo":5,
	"enteco2":2,
	"infocomm":4,
	"gui":5,
	"intel":3,
	"itsec":4,
	"projwork4":2,
	//5th semester
	"management":3,
	"archi":4,
	"eis":4,
	"projwork5":2,
	//6th semester
	"law":3,
	"advarchi1":2,
	"projwork6":2,
	"thesis1":6,
	//7th semester
	"advarchi2":2,
	"projwork7":2,
	"thesis2":9,
	//Specializations
	//IOT, Robotics
	"contreng":4,
	"embedded":4,
	"robotics":4,
	"embeddedprog1":4,
	"robotprog":3,
	"embeddedprog2":4,
	"robot control":3,
	"sensnet":4,
	//Big Data
	"finance":3,
	"advdb":5,
	"warehousing":8,
	"bigdataprog":5,
	"erp1":2,
	"erp2":7,
	//Cloud and IT security
	"nettech1":4,
	"vis":4,
	"ccs1":3,
	"ccs2":2,
	"secucomp":5,
	"secuinfosys":5,
	"institutionsec":7,
	"nettech2":5,
	"virtual":7,	
	//Software
	"parallel":5,
	"largesw":3,
	"dataparallel":2,
	"modernsw":2,
	"adval":4,
	"testing":3,
	"oop":4,
	"datastruct":3,
	"script":4,
	"deeplearn":4,
	"imagefund":3,
	"imageanalyses":4,
	"android1":4,
	"android2":3,
	"iOS":4,
	"JEE":4,
	"WebDev":3,
	"AdvDataProc":4
}
